### ISSUE TITLE
Different behaviour of `send_messages` when SMTP backend is used as context manager

### ISSUE THREAD

**Issue by amureki** [voiio/emark#96]
When using this package's `TrackingSMTPEmailBackend`, I noticed the following behavioural differences:

If I am sending several emails via:

```python
from django.core import mail
messages = [] # list of `emark.message.MarkdownEmail` emails
mail.get_connection().send_messages(messages)
```

The internal flow for these looks like the following:
1. Each of the email gets rendered
2. We are opening an SMTP connection
3. Emails are sent
4. Connection is closed

However, things are different if I am sending the very same emails, but with using a context manager:

```python
from django.core import mail
messages = [] # list of `emark.message.MarkdownEmail` emails
with mail.get_connection() as connection:
    connection.send_messages(messages)
```

1. We are opening an SMTP connection
2. Each of the email gets rendered
3. (if the rendering time is beyond SMTP timeout, connection drops)
3. Emails are sent
4. Connection is closed

And since the rendering (with included tracking) is a heavy operation, I am experiencing SMTP timeout error when sending more than 10 emails.

**Comment by codingjoe** [comment]
Uff, that's a tough one. This isn't really based on anything the package does. Django doesn't call the message method on email instances prior either. Connection timeouts, would be an issue that could face Django either. I believe the only good approach is to prevent users from passing mails that aren't rendered forcing them to render messages in advance.


Or, we submit this to Django and have them use lazy connections or whatever they do, with a connection that's hasn't been entered.
